AWSTemplateFormatVersion: '2010-09-09'
Description: A CloudFormation template to deploy the Stable Diffusion Web UI by Automatic1111

Parameters:
  UsernameParameter:
    Type: String
    Default: admin
    
  PasswordParameter:
    Type: String
    Default: admin

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: sd-webui-sg
      GroupDescription: Security group for SD WebUI EC2 instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 7860
          ToPort: 7860
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8384
          ToPort: 8384
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: g4dn.xlarge
      ImageId: ami-0574da719dca65348
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 300
            VolumeType: gp2
      "Tags" : [
            {"Key" : "Name", "Value" : "sd-web-ui-cf"},
        ]
      SecurityGroups:
        - Ref: SecurityGroup
      UserData:
        'Fn::Base64': |
            #!/bin/bash
            cd /home/ubuntu
            git clone https://github.com/rafabulsing/stable-diffusion-webui-cf.git
            bash stable-diffusion-webui-cf/setup.sh -y >> log.txt

  MyEIP:
    Type: AWS::EC2::EIP
  MyEIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt MyEIP.AllocationId
      InstanceId: !Ref EC2Instance

  Username:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: SecureString
      Name: sd-webui/username
      Value:
        Ref: UsernameParameter
      Tags:
        Group: sd-webui
  Password:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: SecureString
      Name: sd-webui/password
      Value:
        Ref: PasswordParameter
      Tags:
        Group: sd-webui
